### ISSUE TITLE
React and React dom should be peer dependencies

### ISSUE THREAD

**Issue by Aschen** [kobble-io/react#1]
Developer will already have React and will want to manage their React version themselve so it avoid installing 2 versions and have compatibility issues.

**Comment by kevinpiac** [comment]
Hey, good catch! 

It's now the case in v1.0.3 (see https://github.com/kobble-io/react/commit/42274361ef204740dbf8ecccad640596d84ae222)

Thanks for reporting this. It's much appreciated 👍
